version: "3"
services:
  # php service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pusher-middleware-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-network

  # nginx service
  webserver:
    image: nginx:alpine
    container_name: pusher-middleware-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "${PORT:-8282}:80"
    environment:
      - NGINX_HOST=localhost
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./docker/nginx/ssl/:/etc/nginx/ssl/
    networks:
      - app-network

# docker networks
networks:
  app-network:
    driver: bridge
